<?php

namespace Database\Seeders;

use App\Models\Client;
use App\Models\JobLevel;
use App\Models\Lead;
use App\Models\User;
use Illuminate\Database\Seeder;

class ClientSeeder extends Seeder
{
    public function run(): void
    {
        $adminId = User::where('email', 'admin@mowingcrm.test')->value('id');
        $leadIds = Lead::orderBy('id')->take(20)->pluck('id');
        $levelIds = JobLevel::orderBy('sort_order')->pluck('id')->values();

        // 0=Entry, 1=Basic, 2=Intermediate, 3=Advanced, 4=Expert — one per client row below
        $levelIndex = [2, 1, 0, 3, 4, 2, 1, 1, 2, 2, 1, 3, 3, 1, 2, 1, 4, 1, 2, 0];

        $rows = [
            ['name' => 'James Wilson',     'email' => 'james.wilson@email.com',     'phone' => '0412 345 678', 'address' => '12 Maple Street, Sunnybank QLD 4109',        'zone_id' => 1, 'equipment_type_id' => 1, 'recurrence_id' => 3, 'service_types' => ['Mulching'],                  'weed_spray' => 'Yes', 'job_type' => 'Regular',   'charges' => 120.00, 'estimated_time' => '1 hour',      'payment_mode' => 'Cash',    'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Driveway', 'additional_site_instructions' => 'Gate code 1234.',              'special_remarks' => 'Long-term client.',         'notes' => 'Prefers early morning.',                  'latitude' => -27.5832, 'longitude' => 153.0445],
            ['name' => 'Sarah Thompson',    'email' => 'sarah.thompson@email.com',    'phone' => '0423 456 789', 'address' => '34 Oak Avenue, Mount Gravatt QLD 4122',      'zone_id' => 2, 'equipment_type_id' => 2, 'recurrence_id' => 4, 'service_types' => ['Side Shoot'],                'weed_spray' => 'No',  'job_type' => 'Regular',   'charges' => 95.00,  'estimated_time' => '45 mins',     'payment_mode' => 'Online',  'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Street',   'additional_site_instructions' => 'Leave clippings in bin.',      'special_remarks' => null,                        'notes' => 'Prefers morning visits.',                 'latitude' => -27.5469, 'longitude' => 153.0702],
            ['name' => 'Michael Brown',     'email' => 'michael.brown@email.com',     'phone' => '0434 567 890', 'address' => '56 Pine Road, Capalaba QLD 4157',            'zone_id' => 3, 'equipment_type_id' => 3, 'recurrence_id' => 5, 'service_types' => ['Cut & Leave'],               'weed_spray' => 'Yes', 'job_type' => 'Regular',   'charges' => 80.00,  'estimated_time' => '30 mins',     'payment_mode' => 'Online',  'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Driveway', 'additional_site_instructions' => 'Access via side gate.',        'special_remarks' => null,                        'notes' => null,                                      'latitude' => -27.5186, 'longitude' => 153.1871],
            ['name' => 'Emma Davis',        'email' => 'emma.davis@email.com',        'phone' => '0445 678 901', 'address' => '78 Cedar Lane, Aspley QLD 4034',             'zone_id' => 4, 'equipment_type_id' => 1, 'recurrence_id' => 3, 'service_types' => ['Mulching', 'Side Shoot'],    'weed_spray' => 'Yes', 'job_type' => 'Regular',   'charges' => 165.00, 'estimated_time' => '1.5 hours',   'payment_mode' => 'Cash',    'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Premium',   'parking_status' => 'Driveway', 'additional_site_instructions' => 'Two cats, keep gate closed.',  'special_remarks' => 'Premium client.',           'notes' => null,                                      'latitude' => -27.3691, 'longitude' => 153.0234],
            ['name' => 'Robert Johnson',    'email' => 'robert.johnson@email.com',    'phone' => '0456 789 012', 'address' => '90 Elm Close, Indooroopilly QLD 4068',       'zone_id' => 5, 'equipment_type_id' => 4, 'recurrence_id' => 5, 'service_types' => ['Cut & Away Side Shoot'],     'weed_spray' => 'No',  'job_type' => 'Regular',   'charges' => 200.00, 'estimated_time' => '2 hours',     'payment_mode' => 'Online',  'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Premium',   'parking_status' => 'Driveway', 'additional_site_instructions' => 'Large property, 3 acres.',     'special_remarks' => 'Large acreage.',            'notes' => 'Second driveway on west side.',            'latitude' => -27.5097, 'longitude' => 152.9765],
            ['name' => 'Jessica Martinez',  'email' => 'jessica.martinez@email.com',  'phone' => '0467 890 123', 'address' => '15 Gum Tree Drive, Redland Bay QLD 4165',    'zone_id' => 6, 'equipment_type_id' => 2, 'recurrence_id' => 4, 'service_types' => ['Mulching'],                  'weed_spray' => 'Yes', 'job_type' => 'Regular',   'charges' => 110.00, 'estimated_time' => '1 hour',      'payment_mode' => 'Cash',    'payment_status' => 'Pending', 'remarks_type' => 'Pending',   'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Street',   'additional_site_instructions' => null,                            'special_remarks' => 'Pays end of month.',        'notes' => null,                                      'latitude' => -27.6161, 'longitude' => 153.3076],
            ['name' => 'David Lee',         'email' => 'david.lee@email.com',         'phone' => '0478 901 234', 'address' => '27 Wattle Court, Ipswich QLD 4305',          'zone_id' => 7, 'equipment_type_id' => 3, 'recurrence_id' => 3, 'service_types' => ['Side Shoot'],                'weed_spray' => 'No',  'job_type' => 'Regular',   'charges' => 90.00,  'estimated_time' => '45 mins',     'payment_mode' => 'Online',  'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Driveway', 'additional_site_instructions' => null,                            'special_remarks' => null,                        'notes' => null,                                      'latitude' => -27.6168, 'longitude' => 152.7597],
            ['name' => 'Olivia Taylor',     'email' => 'olivia.taylor@email.com',     'phone' => '0489 012 345', 'address' => '43 Banksia Way, Springfield QLD 4300',       'zone_id' => 8, 'equipment_type_id' => 1, 'recurrence_id' => 5, 'service_types' => ['Cut & Leave'],               'weed_spray' => 'Yes', 'job_type' => 'Regular',   'charges' => 85.00,  'estimated_time' => '30 mins',     'payment_mode' => 'Online',  'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Driveway', 'additional_site_instructions' => 'Call before arriving.',        'special_remarks' => null,                        'notes' => null,                                      'latitude' => -27.6672, 'longitude' => 152.9051],
            ['name' => 'Daniel Anderson',   'email' => 'daniel.anderson@email.com',   'phone' => '0490 123 456', 'address' => '61 Grevillea Place, Logan QLD 4114',         'zone_id' => 1, 'equipment_type_id' => 2, 'recurrence_id' => 4, 'service_types' => ['Mulching'],                  'weed_spray' => 'Yes', 'job_type' => 'Regular',   'charges' => 130.00, 'estimated_time' => '1 hour',      'payment_mode' => 'Cash',    'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Street',   'additional_site_instructions' => 'Corner block, two frontages.', 'special_remarks' => null,                        'notes' => null,                                      'latitude' => -27.6389, 'longitude' => 153.1093],
            ['name' => 'Sophia Thomas',     'email' => 'sophia.thomas@email.com',     'phone' => '0401 234 567', 'address' => '82 Bottlebrush Street, Carindale QLD 4152',  'zone_id' => 2, 'equipment_type_id' => 3, 'recurrence_id' => 3, 'service_types' => ['Side Shoot', 'Cut & Leave'], 'weed_spray' => 'No',  'job_type' => 'Regular',   'charges' => 145.00, 'estimated_time' => '1.5 hours',   'payment_mode' => 'Online',  'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Driveway', 'additional_site_instructions' => 'Elderly resident.',            'special_remarks' => null,                        'notes' => 'Be considerate of noise.',                'latitude' => -27.5253, 'longitude' => 153.0921],
            ['name' => 'Matthew Harris',    'email' => 'matthew.harris@email.com',    'phone' => '0412 345 679', 'address' => '19 Jacaranda Ave, Paddington QLD 4064',      'zone_id' => 3, 'equipment_type_id' => 1, 'recurrence_id' => 5, 'service_types' => ['Mulching'],                  'weed_spray' => 'Yes', 'job_type' => 'Regular',   'charges' => 100.00, 'estimated_time' => '1 hour',      'payment_mode' => 'Online',  'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Street',   'additional_site_instructions' => 'Avoid west side (renovating).', 'special_remarks' => null,                        'notes' => null,                                      'latitude' => -27.4625, 'longitude' => 152.9852],
            ['name' => 'Isabella Clark',    'email' => 'isabella.clark@email.com',    'phone' => '0423 456 780', 'address' => '38 Acacia Road, Wynnum QLD 4178',            'zone_id' => 4, 'equipment_type_id' => 2, 'recurrence_id' => 3, 'service_types' => ['Cut & Away Side Shoot'],     'weed_spray' => 'No',  'job_type' => 'Regular',   'charges' => 175.00, 'estimated_time' => '1.5 hours',   'payment_mode' => 'Cash',    'payment_status' => 'Pending', 'remarks_type' => 'Pending',   'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Street',   'additional_site_instructions' => 'Coastal property.',            'special_remarks' => 'Invoiced separately.',      'notes' => null,                                      'latitude' => -27.4581, 'longitude' => 153.1687],
            ['name' => 'Joshua White',      'email' => 'joshua.white@email.com',      'phone' => '0434 567 891', 'address' => '54 Melaleuca Drive, Kenmore QLD 4069',       'zone_id' => 5, 'equipment_type_id' => 3, 'recurrence_id' => 4, 'service_types' => ['Mulching', 'Side Shoot'],    'weed_spray' => 'Yes', 'job_type' => 'Regular',   'charges' => 160.00, 'estimated_time' => '1.5 hours',   'payment_mode' => 'Online',  'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Driveway', 'additional_site_instructions' => 'Mind pool fence clearance.',   'special_remarks' => null,                        'notes' => null,                                      'latitude' => -27.5043, 'longitude' => 152.9392],
            ['name' => 'Charlotte Lewis',   'email' => 'charlotte.lewis@email.com',   'phone' => '0445 678 902', 'address' => '71 Hakea Court, Robina QLD 4226',            'zone_id' => 6, 'equipment_type_id' => 1, 'recurrence_id' => 5, 'service_types' => ['Cut & Leave'],               'weed_spray' => 'No',  'job_type' => 'Regular',   'charges' => 90.00,  'estimated_time' => '45 mins',     'payment_mode' => 'Online',  'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Driveway', 'additional_site_instructions' => null,                            'special_remarks' => null,                        'notes' => 'Gold Coast client.',                      'latitude' => -28.0881, 'longitude' => 153.3863],
            ['name' => 'Andrew Walker',     'email' => 'andrew.walker@email.com',     'phone' => '0456 789 013', 'address' => '88 Eucalyptus Way, Ferny Grove QLD 4055',    'zone_id' => 7, 'equipment_type_id' => 2, 'recurrence_id' => 3, 'service_types' => ['Mulching'],                  'weed_spray' => 'Yes', 'job_type' => 'Regular',   'charges' => 115.00, 'estimated_time' => '1 hour',      'payment_mode' => 'Cash',    'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Driveway', 'additional_site_instructions' => 'Difficult slope on north side.', 'special_remarks' => null,                        'notes' => null,                                      'latitude' => -27.4217, 'longitude' => 152.9334],
            ['name' => 'Ava Hall',          'email' => 'ava.hall@email.com',          'phone' => '0467 890 124', 'address' => '23 Casuarina Street, Wavell Heights QLD 4012', 'zone_id' => 8, 'equipment_type_id' => 3, 'recurrence_id' => 4, 'service_types' => ['Side Shoot'],               'weed_spray' => 'No',  'job_type' => 'Regular',   'charges' => 95.00,  'estimated_time' => '45 mins',     'payment_mode' => 'Online',  'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Street',   'additional_site_instructions' => null,                            'special_remarks' => null,                        'notes' => null,                                      'latitude' => -27.3874, 'longitude' => 153.0518],
            ['name' => 'Ryan Allen',        'email' => 'ryan.allen@email.com',        'phone' => '0478 901 235', 'address' => '47 Paperbark Lane, Mansfield QLD 4122',      'zone_id' => 1, 'equipment_type_id' => 4, 'recurrence_id' => 5, 'service_types' => ['Cut & Away Side Shoot'],     'weed_spray' => 'Yes', 'job_type' => 'Regular',   'charges' => 220.00, 'estimated_time' => '2 hours',     'payment_mode' => 'Online',  'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Premium',   'parking_status' => 'Driveway', 'additional_site_instructions' => 'Vacant property.',             'special_remarks' => 'Landlord pays.',            'notes' => 'Invoice sent to property manager.',       'latitude' => -27.5318, 'longitude' => 153.0885],
            ['name' => 'Mia Young',         'email' => 'mia.young@email.com',         'phone' => '0489 012 346', 'address' => '65 Stringybark Road, Chapel Hill QLD 4069',  'zone_id' => 2, 'equipment_type_id' => 2, 'recurrence_id' => 3, 'service_types' => ['Mulching'],                  'weed_spray' => 'No',  'job_type' => 'Regular',   'charges' => 105.00, 'estimated_time' => '1 hour',      'payment_mode' => 'Cash',    'payment_status' => 'Pending', 'remarks_type' => 'Pending',   'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Street',   'additional_site_instructions' => null,                            'special_remarks' => null,                        'notes' => 'Prefers afternoon slots.',                'latitude' => -27.4938, 'longitude' => 152.9518],
            ['name' => 'Nathan King',       'email' => 'nathan.king@email.com',       'phone' => '0490 123 457', 'address' => '92 Ironbark Drive, Mitchelton QLD 4053',     'zone_id' => 3, 'equipment_type_id' => 1, 'recurrence_id' => 4, 'service_types' => ['Side Shoot', 'Mulching'],    'weed_spray' => 'Yes', 'job_type' => 'Regular',   'charges' => 140.00, 'estimated_time' => '1.5 hours',   'payment_mode' => 'Online',  'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Driveway', 'additional_site_instructions' => 'Veggie garden near east fence.', 'special_remarks' => null,                        'notes' => null,                                      'latitude' => -27.4253, 'longitude' => 152.9847],
            ['name' => 'Grace Scott',       'email' => 'grace.scott@email.com',       'phone' => '0401 234 568', 'address' => '14 Corymbia Close, Eight Mile Plains QLD 4113', 'zone_id' => 4, 'equipment_type_id' => 1, 'recurrence_id' => 5, 'service_types' => ['Cut & Leave'],              'weed_spray' => 'No',  'job_type' => 'Regular',   'charges' => 88.00,  'estimated_time' => '45 mins',     'payment_mode' => 'Online',  'payment_status' => 'Done',    'remarks_type' => 'Standard',  'customer_type' => "Don't Know", 'client_type' => 'Regular',   'parking_status' => 'Driveway', 'additional_site_instructions' => 'Kids play area in backyard.',  'special_remarks' => null,                        'notes' => null,                                      'latitude' => -27.5851, 'longitude' => 153.0953],
        ];

        foreach ($rows as $i => $data) {
            Client::create(array_merge($data, [
                'lead_id' => $leadIds[$i] ?? null,
                'job_level_id' => $levelIds[$levelIndex[$i]] ?? null,
                'created_by' => $adminId,
            ]));
        }
    }
}
