<x-layouts.dashboard :title="'Salary Receipt'">
    <x-ui.breadcrumbs :items="[
        ['label' => 'Dashboard', 'url' => route('dashboard.index')],
        ['label' => 'Salary Receipts', 'url' => route('admin.salary-receipts.index')],
        ['label' => 'Receipt #' . $receipt->id],
    ]" />

    <div class="mx-auto max-w-2xl space-y-5">
        @if (session('success'))
            <div class="rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-700">
                {{ session('success') }}
            </div>
        @endif

        <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <div class="border-b border-dashed border-slate-200 pb-4">
                <h2 class="text-lg font-semibold text-slate-900">Salary Receipt</h2>
                <p class="text-sm text-slate-500">Receipt #{{ $receipt->id }}</p>
            </div>

            <dl class="mt-4 grid grid-cols-2 gap-x-4 gap-y-3 text-sm">
                <div>
                    <dt class="text-xs uppercase tracking-wide text-slate-400">Mower</dt>
                    <dd class="font-medium text-slate-800">{{ $receipt->mower->name ?? '—' }}</dd>
                </div>
                <div>
                    <dt class="text-xs uppercase tracking-wide text-slate-400">Period</dt>
                    <dd class="font-medium text-slate-800">
                        {{ ucfirst($receipt->period_type->value) }}
                        ({{ $receipt->period_start->format('M d') }} - {{ $receipt->period_end->format('M d, Y') }})
                    </dd>
                </div>
                <div>
                    <dt class="text-xs uppercase tracking-wide text-slate-400">Total Sales</dt>
                    <dd class="font-medium text-slate-800">${{ number_format($receipt->total_sales, 2) }}</dd>
                </div>
                <div>
                    <dt class="text-xs uppercase tracking-wide text-slate-400">Bonus</dt>
                    <dd class="font-medium text-slate-800">${{ number_format($receipt->total_bonus, 2) }}</dd>
                </div>
                <div>
                    <dt class="text-xs uppercase tracking-wide text-slate-400">Percentage Applied</dt>
                    <dd class="font-medium text-slate-800">{{ number_format($receipt->percentage_used, 2) }}%</dd>
                </div>
                <div>
                    <dt class="text-xs uppercase tracking-wide text-slate-400">Generated By</dt>
                    <dd class="font-medium text-slate-800">{{ $receipt->generatedBy->name ?? '—' }}</dd>
                </div>
                <div>
                    <dt class="text-xs uppercase tracking-wide text-slate-400">Generated On</dt>
                    <dd class="font-medium text-slate-800">{{ $receipt->created_at->format('M d, Y H:i') }}</dd>
                </div>
            </dl>

            <div class="mt-5 flex items-center justify-between rounded-xl bg-emerald-50 px-4 py-3 cursor-help" title="{{ $receipt->formulaDescription() }}">
                <span class="text-sm font-medium text-emerald-800">Salary Amount</span>
                <span class="text-xl font-bold text-emerald-700">${{ number_format($receipt->salary_amount, 2) }}</span>
            </div>
        </div>

        <div class="flex gap-3">
            <a href="{{ route('admin.salary-receipts.export.pdf', $receipt) }}"
               class="rounded-md border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">
                Download PDF
            </a>
            <a href="{{ route('admin.salary-receipts.index') }}"
               class="rounded-md border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">
                Back to Receipts
            </a>
            @can('delete', $receipt)
                <form method="POST" action="{{ route('admin.salary-receipts.destroy', $receipt) }}"
                      onsubmit="return confirm('Delete this salary receipt? This cannot be undone.');">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="rounded-md border border-red-300 px-4 py-2 text-sm font-medium text-red-700 hover:bg-red-50">
                        Delete Receipt
                    </button>
                </form>
            @endcan
        </div>
    </div>
</x-layouts.dashboard>
