<?php

namespace App\Exports;

use Illuminate\Database\Eloquent\Collection;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Component\HttpFoundation\StreamedResponse;

class LeadsExport
{
    private const HEADER_BG    = '1E3A5F';
    private const HEADER_FG    = 'FFFFFF';
    private const BAND_BG      = 'F0F4F8';
    private const TITLE_BG     = '10B981';
    private const TITLE_FG     = 'FFFFFF';
    private const BORDER_COLOR = 'CBD5E1';
    private const LAST_COL     = 'X';

    private const COLUMNS = [
        'A' => ['header' => '#',                 'width' => 6],
        'B' => ['header' => 'Client Name',        'width' => 24],
        'C' => ['header' => 'Email',              'width' => 28],
        'D' => ['header' => 'Mobile',             'width' => 16],
        'E' => ['header' => 'Address',            'width' => 32],
        'F' => ['header' => 'Zone',               'width' => 16],
        'G' => ['header' => 'Service Types',      'width' => 26],
        'H' => ['header' => 'Equipment Type',     'width' => 18],
        'I' => ['header' => 'Job Type',           'width' => 14],
        'J' => ['header' => 'Charges ($)',        'width' => 13],
        'K' => ['header' => 'Payment Mode',       'width' => 15],
        'L' => ['header' => 'Payment Status',     'width' => 15],
        'M' => ['header' => 'Status',             'width' => 14],
        'N' => ['header' => 'Assigned To',        'width' => 20],
        'O' => ['header' => 'Lead Date',          'width' => 13],
        'P' => ['header' => 'Lead Time',          'width' => 11],
        'Q' => ['header' => 'Converted At',       'width' => 18],
        'R' => ['header' => 'Weed Spray',         'width' => 12],
        'S' => ['header' => 'Re-completion Days', 'width' => 18],
        'T' => ['header' => 'Remarks',            'width' => 30],
        'U' => ['header' => 'Property Details',   'width' => 28],
        'V' => ['header' => 'Latitude',           'width' => 14],
        'W' => ['header' => 'Longitude',          'width' => 14],
        'X' => ['header' => 'Created At',         'width' => 18],
    ];

    public function __construct(private readonly Collection $leads) {}

    public function download(string $filename): StreamedResponse
    {
        $spreadsheet = $this->build();

        return new StreamedResponse(function () use ($spreadsheet): void {
            $writer = new Xlsx($spreadsheet);
            $writer->save('php://output');
        }, 200, [
            'Content-Type'        => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
            'Cache-Control'       => 'max-age=0',
        ]);
    }

    private function build(): Spreadsheet
    {
        $spreadsheet = new Spreadsheet;
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Leads');

        $this->setDocumentProperties($spreadsheet);
        $this->renderTitleBlock($sheet);
        $this->renderHeaders($sheet);
        $this->renderData($sheet);
        $this->applyColumnWidths($sheet);
        $sheet->freezePane('E5');

        return $spreadsheet;
    }

    private function setDocumentProperties(Spreadsheet $spreadsheet): void
    {
        $appName = config('app.name');
        $spreadsheet->getProperties()
            ->setCreator($appName)
            ->setTitle('Leads Export')
            ->setSubject('Leads Report')
            ->setDescription('Generated by ' . $appName);
    }

    private function renderTitleBlock(Worksheet $sheet): void
    {
        $last = self::LAST_COL;

        $sheet->mergeCells('A1:' . $last . '1');
        $sheet->setCellValue('A1', 'LEADS REPORT');
        $sheet->getStyle('A1')->applyFromArray([
            'font'      => ['bold' => true, 'size' => 14, 'color' => ['argb' => 'FF' . self::TITLE_FG]],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FF' . self::TITLE_BG]],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);
        $sheet->getRowDimension(1)->setRowHeight(36);

        $sheet->mergeCells('A2:' . $last . '2');
        $sheet->setCellValue('A2', 'Generated: ' . now()->format('d M Y, H:i') . '   |   Total Records: ' . $this->leads->count());
        $sheet->getStyle('A2')->applyFromArray([
            'font'      => ['size' => 9, 'italic' => true, 'color' => ['argb' => 'FF64748B']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FFF8FAFC']],
        ]);
        $sheet->getRowDimension(2)->setRowHeight(22);
        $sheet->getRowDimension(3)->setRowHeight(6);
    }

    private function renderHeaders(Worksheet $sheet): void
    {
        $last = self::LAST_COL;

        foreach (self::COLUMNS as $col => $def) {
            $sheet->setCellValue($col . '4', $def['header']);
        }

        $sheet->getStyle('A4:' . $last . '4')->applyFromArray([
            'font'      => ['bold' => true, 'size' => 9, 'color' => ['argb' => 'FF' . self::HEADER_FG]],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FF' . self::HEADER_BG]],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'borders'   => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['argb' => 'FF' . self::HEADER_BG]]],
        ]);
        $sheet->getRowDimension(4)->setRowHeight(22);
    }

    private function renderData(Worksheet $sheet): void
    {
        $last = self::LAST_COL;
        $row  = 5;

        foreach ($this->leads as $i => $lead) {
            $isBand = ($i % 2 === 1);

            $sheet->setCellValue('A' . $row, $i + 1);
            $sheet->setCellValue('B' . $row, $lead->client_name ?? '');
            $sheet->setCellValue('C' . $row, $lead->email ?? '');
            $sheet->setCellValueExplicit('D' . $row, (string) ($lead->mobile_number ?? ''), DataType::TYPE_STRING);
            $sheet->setCellValue('E' . $row, $lead->address ?? '');
            $sheet->setCellValue('F' . $row, $lead->zone?->name ?? '');
            $sheet->setCellValue('G' . $row, is_array($lead->service_types) ? implode(', ', $lead->service_types) : '');
            $sheet->setCellValue('H' . $row, $lead->equipmentType?->name ?? '');
            $sheet->setCellValue('I' . $row, $lead->job_type ?? '');
            $sheet->setCellValue('J' . $row, $lead->charges !== null ? (float) $lead->charges : '');
            $sheet->setCellValue('K' . $row, $lead->payment_mode ?? '');
            $sheet->setCellValue('L' . $row, $lead->payment_status ?? '');
            $sheet->setCellValue('M' . $row, $lead->status ?? '');
            $sheet->setCellValue('N' . $row, $lead->assignedSalesUser?->name ?? 'Unassigned');
            $sheet->setCellValue('O' . $row, $lead->lead_date?->format('d/m/Y') ?? '');
            $sheet->setCellValue('P' . $row, $lead->lead_time ?? '');
            $sheet->setCellValue('Q' . $row, $lead->converted_at?->format('d/m/Y H:i') ?? '');
            $sheet->setCellValue('R' . $row, $lead->weed_spray ?? '');
            $sheet->setCellValue('S' . $row, $lead->re_completion_days !== null ? (int) $lead->re_completion_days : '');
            $sheet->setCellValue('T' . $row, $lead->remarks ?? '');
            $sheet->setCellValue('U' . $row, $lead->property_details ?? '');
            $sheet->setCellValue('V' . $row, $lead->latitude !== null ? (float) $lead->latitude : '');
            $sheet->setCellValue('W' . $row, $lead->longitude !== null ? (float) $lead->longitude : '');
            $sheet->setCellValue('X' . $row, $lead->created_at?->format('d/m/Y H:i') ?? '');

            $sheet->getStyle('J' . $row)->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED2);

            $bgColor = $isBand ? 'FF' . self::BAND_BG : 'FFFFFFFF';
            $sheet->getStyle('A' . $row . ':' . $last . $row)->applyFromArray([
                'font'      => ['size' => 9, 'color' => ['argb' => 'FF1E293B']],
                'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => $bgColor]],
                'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
                'borders'   => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['argb' => 'FF' . self::BORDER_COLOR]]],
            ]);

            foreach (['A', 'J', 'O', 'P', 'Q', 'R', 'S', 'V', 'W', 'X'] as $centerCol) {
                $sheet->getStyle($centerCol . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            }

            $sheet->getRowDimension($row)->setRowHeight(18);
            $row++;
        }

        if ($this->leads->isNotEmpty()) {
            $sheet->getStyle('A4:' . $last . ($row - 1))->applyFromArray([
                'borders' => ['outline' => ['borderStyle' => Border::BORDER_MEDIUM, 'color' => ['argb' => 'FF' . self::HEADER_BG]]],
            ]);
            $sheet->getStyle('E5:E' . ($row - 1))->getAlignment()->setWrapText(true);
        }
    }

    private function applyColumnWidths(Worksheet $sheet): void
    {
        foreach (self::COLUMNS as $col => $def) {
            $sheet->getColumnDimension($col)->setWidth($def['width']);
        }
    }
}
