<?php

namespace App\Exports;

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Component\HttpFoundation\StreamedResponse;

abstract class SpreadsheetExport
{
    protected const HEADER_BG    = '1E3A5F';
    protected const HEADER_FG    = 'FFFFFF';
    protected const BAND_BG      = 'F0F4F8';
    protected const TITLE_BG     = '10B981';
    protected const TITLE_FG     = 'FFFFFF';
    protected const BORDER_COLOR = 'CBD5E1';

    /** @return array<string, array{header: string, width: int}> */
    abstract protected function getColumns(): array;

    abstract protected function getLastColumn(): string;

    abstract protected function getTitle(): string;

    abstract protected function getSheetName(): string;

    abstract protected function getRecordCount(): int;

    abstract protected function renderData(Worksheet $sheet): void;

    public function download(string $filename): StreamedResponse
    {
        $spreadsheet = $this->build();

        return new StreamedResponse(function () use ($spreadsheet): void {
            $writer = new Xlsx($spreadsheet);
            $writer->save('php://output');
        }, 200, [
            'Content-Type'        => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
            'Cache-Control'       => 'max-age=0',
        ]);
    }

    private function build(): Spreadsheet
    {
        $spreadsheet = new Spreadsheet;
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle($this->getSheetName());

        $appName = config('app.name');
        $spreadsheet->getProperties()
            ->setCreator($appName)
            ->setTitle($this->getTitle())
            ->setSubject($this->getTitle())
            ->setDescription('Generated by ' . $appName);

        $this->renderTitleBlock($sheet);
        $this->renderHeaders($sheet);
        $this->renderData($sheet);
        $this->applyColumnWidths($sheet);
        $sheet->freezePane('E5');

        $this->afterBuild($spreadsheet);

        return $spreadsheet;
    }

    protected function afterBuild(Spreadsheet $spreadsheet): void {}

    private function renderTitleBlock(Worksheet $sheet): void
    {
        $last = $this->getLastColumn();

        $sheet->mergeCells('A1:' . $last . '1');
        $sheet->setCellValue('A1', strtoupper($this->getTitle()));
        $sheet->getStyle('A1')->applyFromArray([
            'font'      => ['bold' => true, 'size' => 14, 'color' => ['argb' => 'FF' . static::TITLE_FG]],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FF' . static::TITLE_BG]],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);
        $sheet->getRowDimension(1)->setRowHeight(36);

        $sheet->mergeCells('A2:' . $last . '2');
        $sheet->setCellValue('A2', 'Generated: ' . now()->format('d M Y, H:i') . '   |   Total Records: ' . $this->getRecordCount());
        $sheet->getStyle('A2')->applyFromArray([
            'font'      => ['size' => 9, 'italic' => true, 'color' => ['argb' => 'FF64748B']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FFF8FAFC']],
        ]);
        $sheet->getRowDimension(2)->setRowHeight(22);
        $sheet->getRowDimension(3)->setRowHeight(6);
    }

    private function renderHeaders(Worksheet $sheet): void
    {
        $last = $this->getLastColumn();

        foreach ($this->getColumns() as $col => $def) {
            $sheet->setCellValue($col . '4', $def['header']);
        }

        $sheet->getStyle('A4:' . $last . '4')->applyFromArray([
            'font'      => ['bold' => true, 'size' => 9, 'color' => ['argb' => 'FF' . static::HEADER_FG]],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FF' . static::HEADER_BG]],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'borders'   => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['argb' => 'FF' . static::HEADER_BG]]],
        ]);
        $sheet->getRowDimension(4)->setRowHeight(22);
    }

    private function applyColumnWidths(Worksheet $sheet): void
    {
        foreach ($this->getColumns() as $col => $def) {
            $sheet->getColumnDimension($col)->setWidth($def['width']);
        }
    }

    /** @param string[] $centerCols */
    protected function applyRowStyle(Worksheet $sheet, int $row, bool $isBand, array $centerCols = []): void
    {
        $last    = $this->getLastColumn();
        $bgColor = $isBand ? 'FF' . static::BAND_BG : 'FFFFFFFF';

        $sheet->getStyle('A' . $row . ':' . $last . $row)->applyFromArray([
            'font'      => ['size' => 9, 'color' => ['argb' => 'FF1E293B']],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => $bgColor]],
            'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
            'borders'   => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['argb' => 'FF' . static::BORDER_COLOR]]],
        ]);

        foreach ($centerCols as $col) {
            $sheet->getStyle($col . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        }

        $sheet->getRowDimension($row)->setRowHeight(18);
    }

    protected function applyOutlineBorder(Worksheet $sheet, int $lastRow): void
    {
        $last = $this->getLastColumn();
        $sheet->getStyle('A4:' . $last . $lastRow)->applyFromArray([
            'borders' => ['outline' => ['borderStyle' => Border::BORDER_MEDIUM, 'color' => ['argb' => 'FF' . static::HEADER_BG]]],
        ]);
    }
}
