<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
@include('admin.partials.export-pdf-styles')
</head>
<body>
    <div class="title-block">
        <h1>SALARY RECEIPT</h1>
        <p>Receipt #{{ $receipt->id }} &nbsp;&bull;&nbsp; Generated: {{ $receipt->created_at->format('d M Y, H:i') }}</p>
    </div>

    <table>
        <colgroup>
            <col style="width:30%">
            <col style="width:70%">
        </colgroup>
        <tbody>
            <tr>
                <td><strong>Mower</strong></td>
                <td>{{ $receipt->mower->name ?? '—' }}</td>
            </tr>
            <tr>
                <td><strong>Period</strong></td>
                <td>{{ ucfirst($receipt->period_type->value) }} ({{ $receipt->period_start->format('d/m/Y') }} - {{ $receipt->period_end->format('d/m/Y') }})</td>
            </tr>
            <tr>
                <td><strong>Total Sales</strong></td>
                <td>${{ number_format($receipt->total_sales, 2) }}</td>
            </tr>
            <tr>
                <td><strong>Bonus</strong></td>
                <td>${{ number_format($receipt->total_bonus, 2) }}</td>
            </tr>
            <tr>
                <td><strong>Percentage Applied</strong></td>
                <td>{{ number_format($receipt->percentage_used, 2) }}%</td>
            </tr>
            <tr>
                <td><strong>Salary Amount</strong></td>
                <td><strong>${{ number_format($receipt->salary_amount, 2) }}</strong></td>
            </tr>
            <tr>
                <td><strong>Generated By</strong></td>
                <td>{{ $receipt->generatedBy->name ?? '—' }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">{{ config('app.name') }} &bull; Generated {{ now()->format('d M Y H:i') }}</div>
</body>
</html>
