@php $isMower = auth()->user()?->hasRole(\App\Support\CrmRoles::MOWER); @endphp
<x-ui.table :headers="$isMower
    ? ['Period', 'Total Sales', 'Bonus', 'Percentage', 'Salary Amount', 'Receipt']
    : ['Mower', 'Period', 'Total Sales', 'Bonus', 'Percentage', 'Salary Amount', 'Generated By', 'Actions']">
    @forelse ($receipts as $receipt)
        <tr>
            @unless ($isMower)
                <td class="px-4 py-3">
                    <p class="font-medium text-slate-800">{{ $receipt->mower->name ?? '—' }}</p>
                    <p class="text-xs text-slate-500">#{{ $receipt->mower->user_unique_id ?? '' }}</p>
                </td>
            @endunless
            <td class="whitespace-nowrap px-4 py-3 text-sm text-slate-700">
                {{ ucfirst($receipt->period_type->value) }}
                <br>
                <span class="text-xs text-slate-500">{{ $receipt->period_start->format('M d') }} - {{ $receipt->period_end->format('M d, Y') }}</span>
            </td>
            <td class="px-4 py-3 text-sm text-slate-700">${{ number_format($receipt->total_sales, 2) }}</td>
            <td class="px-4 py-3 text-sm text-slate-700">${{ number_format($receipt->total_bonus, 2) }}</td>
            <td class="px-4 py-3 text-sm text-slate-700">{{ number_format($receipt->percentage_used, 2) }}%</td>
            <td class="px-4 py-3 text-sm font-semibold text-emerald-700 cursor-help"
                title="{{ $receipt->formulaDescription() }}">
                ${{ number_format($receipt->salary_amount, 2) }}
            </td>
            @unless ($isMower)
                <td class="px-4 py-3 text-sm text-slate-600">{{ $receipt->generatedBy->name ?? '—' }}</td>
            @endunless
            <td class="whitespace-nowrap px-4 py-3">
                <div class="flex gap-2">
                    <a href="{{ route('admin.salary-receipts.show', $receipt) }}"
                       class="rounded-md border border-slate-300 px-2 py-1 text-xs hover:bg-slate-50">
                        View
                    </a>
                    <a href="{{ route('admin.salary-receipts.export.pdf', $receipt) }}"
                       class="rounded-md border border-slate-300 px-2 py-1 text-xs hover:bg-slate-50">
                        PDF
                    </a>
                    @can('delete', $receipt)
                        <button type="button"
                                class="delete-salary-receipt rounded-md border border-red-300 px-2 py-1 text-xs text-red-700 hover:bg-red-50"
                                data-id="{{ $receipt->id }}">
                            Delete
                        </button>
                    @endcan
                </div>
            </td>
        </tr>
    @empty
        <tr>
            <td colspan="{{ $isMower ? 6 : 8 }}" class="px-4 py-10 text-center text-sm text-slate-400">
                No salary receipts found.
            </td>
        </tr>
    @endforelse
</x-ui.table>

<div class="mt-4">{{ $receipts->links() }}</div>
